### PR TITLE
Feature - UI for AI Chat

### PR DESCRIPTION
**Pull request by abhiroopc84**
### Description

Implemented the AI Chat UI as mentioned in #550. I've increased the width of the EditPanel to accommodate the UI elements better, we can decide on a default width once the resizable EditPanel implementation is done.

image
image

### What is the purpose of this pull request? 

- [X] New feature
- [ ] Documentation update
- [ ] Bug fix
- [ ] Refactor
- [ ] Release
- [ ] Other

### CODE REVIEW

**Comment by drfarrell** [comment]
I did an initial pass through just tidying some stuff up, but I think we'll have a better idea of what the next phase of this will be when we have some of the first AI features together. @Kitenite what do you think?

**Comment by abhiroopc84** [comment]
Which model are you planning to use for the AI features @drfarrell ?

**Comment by Kitenite** [comment]
@abhiroopc84 , I've used openai in the past and their API is always improving so likely that. I personally use claude so will give the docs a look before I lock down to one.

**Comment by abhiroopc84** [comment]
@Kitenite are you planning on fine tuning the model to better perform for our use case? Last I checked, I think Claude does support fine tuning their model, but OpenAI didn't yet support it.

**Comment by Kitenite** [comment]
@abhiroopc84 No plans as of yet. We'll start with some baseline performance, gather some feedback and decide how we want to proceed. There are a lot of different use cases we want to try before optimizing any particular one.

**Review by Kitenite — APPROVED** [review]
Oh man I'm excited for this! Nice work

**Pull request merged**
