### PR TITLE
Improved the color styling for lightmode on the opening screen

### PR DESCRIPTION
**Pull request by Kabiirk**
### Description

Fixes Issue #579.

**Requirement:**
Improve the color styling for lightmode on the opening screen

**Implementation:**
I followed the "inversion" approach (with modifications) & created the better-suited colors for Light & dark mode.

### What is the purpose of this pull request? 

- [ ] New feature
- [ ] Documentation update
- [x] Bug fix
- [x] Refactor
- [ ] Release
- [ ] Other

### CODE REVIEW

**Review by drfarrell — CHANGES_REQUESTED** [review]
This is way too complex of a solution 😅 You can achieve this with existing tokens we already have defined in the tailwind config. Try dark: and regular classes on the appropriate locations.

**Comment by Kabiirk** [comment]
I don't think all the colors used in the "new projects" screen are defined in tailwind config/css vars. There were some teal, grey, black & white shades, but no blues. So I think I'd still have to add most of `Teal-x` & all of `Blue-x` CSS variables & Tailwind classes (with shorter names)

I do understand that these maybe too many CSS variables though (with very long names). 

Are you suggesting that I can do the following in `ChooseMethod.tsx` ? : 
```typescript
<Card className="w-full
                 border

                 // dark Theme
                 dark:border-blue-800
                 dark:bg-blue-950
                 dark:hover:bg-blue-900
                 dark:hover:border-blue-600

                 // light Theme
                 border-blue-300
                 bg-blue-100
                 hover:bg-blue-200
                 hover:border-blue-400

                 hover:cursor-pointer"
                 // ... " other classes
                 onClick={() => {
                       setCreateMethod(CreateMethod.NEW);
                 }}>
```

instead of my initial implementation : 
```typescript
<Card className="w-full
                 border border-np-primary-card-border
                 bg-np-primary-card-background
                 hover:bg-np-primary-card-background-hover
                 hover:border-np-primary-card-border-hover
                 hover:cursor-pointer
                 flex
                 flex-col"
                 // ... " other classes
                 onClick={() => {
                       setCreateMethod(CreateMethod.NEW);
                 }}>
```

I can do that for sure, but wouldn't that inflate the classes in the element itself ? As mentioned above, I'd still need to define the extra colors so I'm not sure if I'd be reducing a lot of changes in `tailwind.config.mjs` & `index.css`.

**Comment by drfarrell** [comment]
Ah I see what you're going for – thanks for clarifying and my apologies for the quick review. What do you imagine "np" stands for?

**Comment by Kabiirk** [comment]
np - "New Project"

Let me know if the class names and hex color work for you in index. I feel the 'np' can be dropped and I can change it to HSV values. You can use these colors somwhere else too.

Happy to change them if required.

**Review by Kitenite — APPROVED** [review]
This looks good. Thanks for setting up the new tokens. Sorry about the delay :)

**Comment by Kabiirk** [comment]
Thanks ! Really appreciate your further refinements. Delay is not a problem :)

**Pull request merged**
