### PR TITLE
Update cursor group in style models

### PR DESCRIPTION
**Pull request by Suvendu-UI**
### Description

this is adding custom cursor style options for the users and solving issue #565 

### What is the purpose of this pull request? 

- [X] New feature
- [ ] Documentation update
- [ ] Bug fix
- [ ] Refactor
- [ ] Release
- [ ] Other

Screenshot 2024-10-25 154413

### CODE REVIEW

**Comment by Suvendu-UI** [comment]
Hey @Kitenite have filed the pr

**Review by Kitenite — CHANGES_REQUESTED** [review]
The intention is to set the CSS cursor value on the element, not so much to change the cursor type. As such, there is no need to use commander. You can just build the UI to choose a cursor type as the issue outline. 

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by Suvendu-UI** [comment]
so you want to have specifically only those 6 cursor shapes not so much which i showed.

**Comment by Suvendu-UI** [comment]
so onclicking the button do you want the design of cursor or not ?

**Comment by Kitenite** [comment]
> so onclicking the button do you want the design of cursor or not ?

As mentioned in the comment, the cursor change is to the element being targeted, not the actual user's cursor.

**Comment by Suvendu-UI** [comment]
ok so just cursor design change if click or hover on that targeted element

**Comment by Kitenite** [comment]
@Suvendu-UI , it's meant to apply a CSS cursor style similar to the other inputs
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by Kitenite** [comment]
Close for inactivity

**Pull request closed without merging**
