### PR TITLE
Bugfix/styles min values

### LINKED ISSUE #147: [Bug] Need minimum values for numeric style inputs that can't be negative
- [ ] Corner / Border radius can't be negative, and shouldn't go lower than 0
- [ ] Padding can't be negative, and shouldn't go lower than 0
- [ ] Width can't be negative
- [ ] Height can't be negative
- [ ] Font size can't be negative
- [ ] Opacity can't be negative

HOWEVER, 
- GAP in flexbox can be negative
- Letter can be negative

### PR DESCRIPTION
**Pull request by cleobnvntra**
### Description

Fixes #147

Enforced the implemented min/max values for the styles and displays a toast with an appropriate message for invalid inputs.

#### Validation

This validation is implemented mainly on the input handlers and handleNumberInputKeyDown methods used by the Single and Compound Styles.

```typescript
const { min, max } = elementStyle.params || {};
if (min !== undefined && parsedNum < min) {
    toast({
        title: 'Invalid Input',
        description: `Value for ${elementStyle.displayName} cannot be less than ${min}`,
        variant: 'destructive',
    });
    return;
}

if (max !== undefined && parsedNum > max) {
    toast({
        title: 'Invalid Input',
        description: `Value for ${elementStyle.displayName} cannot be greater than ${max}`,
        variant: 'destructive',
    });
    return;
}
```

#### Constraint values

A simple object to easily modify the min/max values for Compound Style groups.

```typescript
const STYLE_CONSTRAINTS = {
    margin: {
        min: 0,
        max: 1000,
    },
    padding: {
        min: 0,
        max: 1000,
    },
    border: {
        radius: {
            min: 0,
            max: 9999,
        },
        width: {
            min: 0,
            max: 1000,
        },
    },
};
```

#### How it looks
Inputting a negative number or pressing arrow down key to go below 0 on the head of the style.
image

Inputting a negative number or pressing arrow down key to go below 0 on the children styles.
image

### What is the purpose of this pull request? 

- [ ] New feature
- [ ] Documentation update
- [x] Bug fix
- [ ] Refactor
- [ ] Release
- [ ] Other

### CODE REVIEW

**Review by Kitenite — APPROVED** [review]
Wowow this is awesome. Great work!

**Comment by cleobnvntra** [comment]
Happy to contribute!

May I ask to have the `hacktoberfest-accepted` label to this PR please?

**Comment by Kitenite** [comment]
Ofc, sorry I missed this

**Comment by cleobnvntra** [comment]
Appreciate it!

**Pull request merged**
